Catch Inventory RBAC error
beav/kerlescan pull request #55
Opened 2020-10-19 21:46 UTC by CodeHeeler

2020-10-20 15:32 UTC, eherget requested changes

2020-10-20 15:32 UTC, eherget commented on kerlescan/inventory_service_interface.py
> +        raise HTTPError(HTTPStatus.FORBIDDEN, message=error.message)
I would prefer to see the HTTPError raised in the interface code that implements our service API endpoint.  We don't want to raise HTTP-specific exceptions that then ties this shared/common code to a HTTP implementation.  The RBACDenied exception should be caught up in drift-backend drift/views/v1.py and the HTTPError raised there.

2020-10-20 15:34 UTC, CodeHeeler commented on kerlescan/inventory_service_interface.py
> +        raise HTTPError(HTTPStatus.FORBIDDEN, message=error.message)
I thought about that as we're already catching other exceptions in a try except block in the drift view, but was thinking we wanted to be short circuiting the process  early and threw it in kerlescan instead.  Your thoughts make sense as a better practice; I'll make the change.

2020-10-26 19:06 UTC, CodeHeeler commented
Moving this work to drift-backend views instead of kerlescan

2020-10-26 19:06 UTC, closed without merging